# Site settings
title: Ryan T. Mahler
email: ryantmer@gmail.com
description: ""
baseurl: ""
url: "http://www.mahler.ca"
github_username:  ryantmer
facebook_username: ryantmer
youtube_channelname: channel/UCH-KiusKhG8N7W1Q04E24BA

# Build settings
markdown: kramdown
permalink: pretty
source: .
destination: _site
safe: false
exclude: []
include: []
timezone: America/Vancouver

collections:
    vsromophas:
        output: false
    archive:
        output: false
